apiVersion: v1
kind: ServiceAccount
metadata:
  name: tasky-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tasky-sa-cluster-admin
subjects:
  - kind: ServiceAccount
    name: tasky-sa
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
