# NOTE: This is a placeholder showing the structure.
# In production, use External Secrets Operator or AWS Secrets Manager CSI driver
# For this exercise, we'll pass MONGO_URI as an environment variable configured during deployment
#
# The MONGO_URI format will be: mongodb://username:password@<EC2_PRIVATE_IP>:27017/tasky?authSource=admin
#
# To manually create the secret after getting credentials:
# kubectl create secret generic mongodb-credentials \
#   --from-literal=username=admin \
#   --from-literal=password=your-password \
#   --from-literal=host=<EC2_PRIVATE_IP>
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
type: Opaque
stringData:
  # These will be populated during deployment or manually
  username: "admin"
  password: "REPLACE_ME"
  host: "<EC2_PRIVATE_IP>"
