apiVersion: v2
name: tasky-app
description: A Helm chart for the Wiz exercise Tasky application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - wiz
  - exercise
  - todo
  - mongodb
maintainers:
  - name: Wiz Exercise
# Trigger redeploy
